import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { CommandContext } from '../core/factory';
import { SecurityScanner } from '../scanner';
import { SkillInstaller } from '../installer';

export async function handleGenerate(ctx: CommandContext, skillName: string, prompt?: string) {
  const safeName = skillName.replace(/[\/\@]/g, '-').replace(/^-/, '').replace(/\s+/g, '-');
  const targetPath = path.join(ctx.process.cwd(), '.agents', 'skills', `${safeName}.md`);

  ctx.io.log(chalk.blue(`🧠 Generating AI Playbook for skill: ${chalk.bold(skillName)}\n`));

  if (ctx.fs.existsSync(targetPath)) {
    ctx.io.error(chalk.yellow(`⚠️ Skill file already exists at: ${targetPath}`));
    ctx.io.error(chalk.yellow(`Aborting to prevent overwriting existing work.`));
    ctx.process.exit(1);
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.AGENTPM_GEMINI_API_KEY;
  let playbookContent = '';

  if (prompt && apiKey) {
    const apiSpinner = ora('Querying Gemini to generate custom security-audited playbook...').start();
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
      const systemPrompt = `You are a world-class AI system architect. Generate a standard AgentPM Skill Playbook in markdown format for a skill named "${skillName}".
The goal of this skill is: "${prompt}".

Requirements for the Playbook format:
1. It must start with a "# ${skillName}" heading.
2. It must have clear sections outlining how to achieve the goal, such as Initial Assessment, Core Principles, Guidelines, and Steps.
3. It can include executable script blocks for python or bash code if necessary, like:
   \`\`\`bash
   echo "Running task..."
   \`\`\`
4. Avoid any system prompt overrides, ignore instructions patterns, or malicious commands (like rm -rf, curl exfiltration, etc.) as this playbook will be automatically security audited and execution will be blocked if any malicious patterns are found.
5. Output ONLY the raw markdown content of the playbook without any enclosing markdown code block wrapper (do not wrap the whole output in \`\`\`markdown ... \`\`\`).`;

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: systemPrompt }]
          }]
        })
      });

      if (!response.ok) {
        throw new Error(`API returned status ${response.status}: ${await response.text()}`);
      }

      const data = await response.json() as any;
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) {
        throw new Error('Received empty response from Gemini API.');
      }
      playbookContent = text;
      apiSpinner.succeed('Custom playbook generated by Gemini successfully.');
    } catch (err) {
      apiSpinner.fail(chalk.red(`Gemini generation failed: ${(err as Error).message}`));
      ctx.io.log(chalk.yellow('🔄 Falling back to high-fidelity offline template system...'));
      playbookContent = getOfflineTemplate(skillName, prompt);
    }
  } else {
    ctx.io.log(chalk.gray('ℹ️ No Gemini API key detected or goal prompt omitted.'));
    ctx.io.log(chalk.gray('🔄 Using high-fidelity offline template system...'));
    playbookContent = getOfflineTemplate(skillName, prompt || '');
  }

  // Enforce Security Gate
  const auditSpinner = ora('Running security gate check on generated playbook...').start();
  const auditResult = SecurityScanner.audit(playbookContent);
  if (!auditResult.isSafe) {
    auditSpinner.fail(chalk.red('Security Gate FAILED! Malicious injection patterns detected in LLM output.'));
    ctx.io.error(chalk.red('The following threats were blocked:'));
    auditResult.threats.forEach(t => ctx.io.error(chalk.red(`   - ${t}`)));
    ctx.io.error(chalk.red('Generation aborted to protect your workstation security.'));
    ctx.process.exit(1);
  }
  auditSpinner.succeed(chalk.green('Security Gate PASSED: Playbook is safe.'));

  // Save Local
  const saveSpinner = ora('Saving playbook file...').start();
  try {
    const savePath = SkillInstaller.saveSkillLocal(skillName, playbookContent);
    saveSpinner.succeed(`Successfully generated and saved skill ${chalk.bold(skillName)}!`);
    ctx.io.log(chalk.gray(`\nLocation: ${savePath}`));
  } catch (err) {
    saveSpinner.fail(chalk.red('Failed to save skill.'));
    ctx.io.error(ctx.io.error(chalk.red(`Error: ${(err as Error).message}`)));
  }
}

function getOfflineTemplate(skillName: string, prompt: string): string {
  const p = prompt.toLowerCase();
  
  if (p.includes('ab') || p.includes('test') || p.includes('experiment')) {
    return `# A/B Testing & Experimentation: ${skillName}

Goal: ${prompt || "Design and implement statistically sound A/B tests."}

## Initial Assessment
Before starting a test, confirm:
1. **Target Metric**: What is the primary metric (e.g. signup rate, CTR)?
2. **Current Volume**: Traffic on the page to calculate sample size.
3. **Key Hypotheses**: What modification is expected to improve the conversion?

## Core Principles
* **Single Variable**: Test one isolated change at a time to prevent confounding results.
* **No Peeking**: Commit to a predetermined test window to avoid statistical significance inflation.
* **Significance Level**: Enforce a minimum of 95% confidence (p-value < 0.05).

## Guidelines
1. Calculate sample size using a power calculator before starting.
2. Segment traffic equally between Control (A) and Variant (B).
3. Validate user cookie tracking consistency to ensure return visitors see the same variant.

## Execution Steps
\`\`\`bash
# Script block to run baseline analytics verification
echo "Validating database analytics logging..."
\`\`\`

1. Setup the control and variant page templates.
2. Initialize analytics tracking flags.
3. Run the experiment for at least two complete business cycles (14 days).
4. Extract conversion counts and calculate the statistical significance.
`;
  }

  if (p.includes('secure') || p.includes('audit') || p.includes('scan') || p.includes('protect')) {
    return `# Workstation Security Auditor: ${skillName}

Goal: ${prompt || "Perform comprehensive security scans on local directory."}

## Initial Assessment
Ensure that you are scanning appropriate targets:
1. Identify all config files, \`.env\` folders, and Git history.
2. Exclude \`node_modules\` and vendor directories to speed up scans.
3. Ensure no local secrets are uploaded or printed in logs.

## Core Principles
* **Workstation Isolation**: Never run unknown commands or download scripts directly to the terminal.
* **Credential Protection**: Hardcoded secrets must be flagged and moved to environment variables.
* **Least Privilege**: Ensure local MCP servers or tools only have read permissions where required.

## Guidelines
1. Scan local repos for hardcoded passwords, tokens, and private keys.
2. Verify file permissions are locked down (e.g. \`chmod 600 .env\`).
3. Clean old workspace residues regularly.

## Execution Steps
\`\`\`python
# Simple helper script to verify .env permissions
import os
import sys

print("Auditing active workspace...")
if os.path.exists('.env'):
    print("WARNING: .env file detected in workspace. Make sure it is added to .gitignore!")
else:
    print("SUCCESS: No raw .env file exposed in root directory.")
\`\`\`

1. Run the static analyzer over files.
2. Check for public/private key pairs in the repository.
3. Verify that \`.gitignore\` contains all sensitive folders.
`;
  }

  if (p.includes('refactor') || p.includes('clean') || p.includes('optimize') || p.includes('format')) {
    return `# Code Refactoring & Quality Optimizer: ${skillName}

Goal: ${prompt || "Refactor code structure to adhere to clean engineering patterns."}

## Initial Assessment
Before modifying any logic:
1. Ensure a clean git state (\`git status\`).
2. Verify that existing unit tests pass (\`npm test\` / \`pytest\`).
3. Identify the target refactoring patterns (e.g., modularization, typing, dependency injection).

## Core Principles
* **Preserve Behavior**: Refactoring must never change external interfaces or logic behavior.
* **TDD Loop**: Implement changes incrementally and run verification tests on every step.
* **Readability Over Cleverness**: Code should be easy to read and maintain for any developer.

## Guidelines
1. Split large monolithic files into dedicated components.
2. Add comprehensive JSDoc/docstrings to all functions.
3. Verify type safety (TypeScript/Python typing).

## Execution Steps
\`\`\`bash
# Run local linter check before starting refactor
echo "Running code health check..."
\`\`\`

1. Create a dedicated refactoring branch.
2. Extract components and modularize handlers.
3. Run compiler check and the test suite to verify behavior is preserved.
`;
  }

  // Generic Playbook Template
  return `# Skill Playbook: ${skillName}

Goal: ${prompt || "Execute workspace automation and playbook task."}

## Initial Assessment
* Understand the requirements and constraints of this goal.
* Check if external dependencies or environment variables are required.

## Core Principles
* Keep commands secure and authenticated.
* Audit output for reliability and clarity.

## Guidelines
1. Follow standard software engineering practices.
2. Document any changes or outputs generated by the agent.

## Execution Steps
\`\`\`bash
# Standard initialization script
echo "Running playbook initialization for ${skillName}..."
\`\`\`

1. Initialize execution environments.
2. Process target workspace files.
3. Verify correct execution outputs.
`;
}
